-- Xcodebuild keymaps — buffer-local so they (and the <leader>m "xcode" group)
-- only surface in swift buffers, never globally in which-key. xcodebuild.nvim
-- loads via ft=swift, so the :Xcodebuild* commands exist whenever these can
-- fire.
--
-- <leader>m ("make") is used instead of <leader>X: it needs no Shift and,
-- unlike <leader>X, never collides with GAF's global Xdebug maps
-- (lua/gaf/xdebug.lua) — so these are set in every swift buffer, GAF or not.
local function map(lhs, rhs, desc, mode)
  vim.keymap.set(mode or "n", lhs, rhs, { buffer = true, desc = desc })
end

map("<leader>mm", "<cmd>XcodebuildPicker<cr>", "All xcodebuild actions")
map("<leader>mS", "<cmd>XcodebuildSetup<cr>", "Setup project (scheme/device/buildServer)")
map("<leader>mb", "<cmd>XcodebuildBuild<cr>", "Build")
map("<leader>mB", "<cmd>XcodebuildBuildForTesting<cr>", "Build for testing")
map("<leader>mr", "<cmd>XcodebuildBuildRun<cr>", "Build & run")
map("<leader>ml", "<cmd>XcodebuildToggleLogs<cr>", "Toggle logs")
map("<leader>me", "<cmd>XcodebuildTestExplorerToggle<cr>", "Test explorer")
map("<leader>mc", "<cmd>XcodebuildToggleCodeCoverage<cr>", "Toggle coverage")
map("<leader>mC", "<cmd>XcodebuildShowCodeCoverageReport<cr>", "Coverage report")
map("<leader>ms", "<cmd>XcodebuildSelectScheme<cr>", "Select scheme")
map("<leader>md", "<cmd>XcodebuildSelectDevice<cr>", "Select device")
map("<leader>mt", "<cmd>XcodebuildSelectTestPlan<cr>", "Select test plan")
map("<leader>mp", "<cmd>XcodebuildPreviewGenerateAndShow<cr>", "SwiftUI preview")
map("<leader>mP", "<cmd>XcodebuildPreviewToggle<cr>", "Toggle SwiftUI preview")
map("<leader>mf", "<cmd>XcodebuildProjectManager<cr>", "Project manager (files/targets)")
-- :XcodebuildCodeActions is just vim.lsp.buf.code_action() — use the global
-- <leader>ca (actions-preview) instead. :XcodebuildQuickfixLine below is the
-- same call with apply=true (auto-fix the line's diagnostic); no global equiv.
map("<leader>mq", "<cmd>XcodebuildQuickfixLine<cr>", "Quickfix (auto-fix line diagnostic)")

-- Buffer-local "xcode" group label (no-op if which-key isn't loaded yet).
pcall(function()
  require("which-key").add({ { "<leader>m", group = "xcode", buffer = 0 } })
end)

-- buildServer.json (what sourcekit-lsp needs to resolve symbols across an
-- .xcodeproj/.xcworkspace; plain SPM Package.swift needs none) is generated by
-- xcodebuild.nvim's own xcode-build-server integration — it runs
-- `xcode-build-server config` + restarts sourcekit on :XcodebuildSetup (<leader>mS)
-- and on every scheme change. No custom regen command needed.

-- Tests — mirrors the neotest <leader>t* convention (config/autocmds.lua);
-- swift uses xcodebuild's own runner, there is no neotest adapter.
map("<leader>tr", "<cmd>XcodebuildTestNearest<cr>", "Run nearest test")
map("<leader>tf", "<cmd>XcodebuildTestClass<cr>", "Run class tests")
map("<leader>tt", "<cmd>XcodebuildTest<cr>", "Run test plan")
map("<leader>ts", "<cmd>XcodebuildTestSelected<cr>", "Run selected tests", "v")
map("<leader>t.", "<cmd>XcodebuildTestRepeat<cr>", "Repeat last tests")
map("<leader>tF", "<cmd>XcodebuildTestFailing<cr>", "Run failing tests")

-- Debug — extends the global <leader>d* DAP maps (lua/plugins/dap.lua).
map("<leader>dd", function() require("xcodebuild.integrations.dap").build_and_debug() end, "Build & debug")
map("<leader>dr", function() require("xcodebuild.integrations.dap").debug_without_build() end, "Debug without build")
map("<leader>td", function() require("xcodebuild.integrations.dap").debug_func_test() end, "Debug nearest test")
